"""Private local/GCS storage. Object keys are generated by the server, never filenames."""
from pathlib import Path


class Storage:
    def __init__(self, config):
        self.config = config
        self.root = (Path(config.data_dir) / 'objects').resolve()
        self.root.mkdir(parents=True, exist_ok=True)

    def _path(self, key):
        path = (self.root / key).resolve()
        if not path.is_relative_to(self.root):
            raise ValueError('Unsafe object key.')
        return path

    def put(self, key, data, mime):
        if self.config.storage_provider == 'gcs':
            from google.cloud import storage
            storage.Client(project=self.config.google_cloud_project).bucket(self.config.gcs_bucket).blob(key).upload_from_string(data, content_type=mime)
        else:
            path = self._path(key)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)

    def get(self, key):
        if self.config.storage_provider == 'gcs':
            from google.cloud import storage
            return storage.Client(project=self.config.google_cloud_project).bucket(self.config.gcs_bucket).blob(key).download_as_bytes()
        return self._path(key).read_bytes()

    def put_immutable(self, key, data, mime):
        """Create-only storage. Duplicate bytes are idempotent; replacements are rejected."""
        if self.config.storage_provider == 'gcs':
            from google.cloud import storage
            from google.api_core.exceptions import PreconditionFailed
            blob = storage.Client(project=self.config.google_cloud_project).bucket(self.config.gcs_bucket).blob(key)
            try:
                blob.upload_from_string(data, content_type=mime, if_generation_match=0)
            except PreconditionFailed:
                if blob.download_as_bytes() != data:
                    raise ValueError('Immutable object collision.')
        else:
            import os
            import tempfile
            path = self._path(key)
            path.parent.mkdir(parents=True, exist_ok=True)
            # Atomically link a complete temporary file: crash cannot leave a partial final object.
            fd, temporary = tempfile.mkstemp(dir=path.parent, prefix='.intake-')
            try:
                with os.fdopen(fd, 'wb') as handle:
                    handle.write(data)
                    handle.flush()
                    os.fsync(handle.fileno())
                try:
                    os.link(temporary, path)
                except FileExistsError:
                    if path.read_bytes() != data:
                        raise ValueError('Immutable object collision.')
            finally:
                os.unlink(temporary)

    def delete(self, key):
        if self.config.storage_provider == 'gcs':
            from google.cloud import storage
            from google.api_core.exceptions import NotFound
            try:
                storage.Client(project=self.config.google_cloud_project).bucket(self.config.gcs_bucket).blob(key).delete()
            except NotFound:
                pass
        else:
            self._path(key).unlink(missing_ok=True)

    def get_bounded(self, key, maximum):
        """Read at most maximum+1 bytes; reject excess before returning any content."""
        if not 1 <= maximum <= 32_000_000:
            raise ValueError('Invalid read bound.')
        if self.config.storage_provider == 'gcs':
            from google.cloud import storage
            from google.api_core.exceptions import NotFound
            try:
                data = storage.Client(project=self.config.google_cloud_project).bucket(self.config.gcs_bucket).blob(key).download_as_bytes(
                    start=0, end=maximum, raw_download=True, timeout=30, retry=None)
            except NotFound as exc:
                raise FileNotFoundError('Stored object is missing.') from exc
        else:
            import os
            import stat
            fd = os.open(self._path(key), os.O_RDONLY | os.O_NONBLOCK)
            with os.fdopen(fd, 'rb') as handle:
                if not stat.S_ISREG(os.fstat(handle.fileno()).st_mode):
                    raise ValueError('Stored object is not a regular file.')
                data = handle.read(maximum+1)
        if len(data) > maximum:
            raise OverflowError('Stored object exceeds its read bound.')
        return data
