"""immutable source intake and shared request budget"""
from alembic import op
import sqlalchemy as sa

revision = '0002_intake'
down_revision = '0001_v040'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sec_request_budget',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('next_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.execute("INSERT INTO sec_request_budget (name, next_at) VALUES ('shared', 0)")
    op.create_table('intake_works',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('family_id', sa.String(length=80), nullable=False),
    sa.Column('work_id', sa.String(length=160), nullable=False),
    sa.Column('edition', sa.String(length=80), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'work_id', 'edition'),
    sa.UniqueConstraint('source_id')
    )
    with op.batch_alter_table('intake_works', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intake_works_family_id'), ['family_id'], unique=False)

    op.create_table('source_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_id', sa.String(length=36), nullable=False),
    sa.Column('raw_sha256', sa.String(length=64), nullable=False),
    sa.Column('object_key', sa.String(length=250), nullable=False),
    sa.Column('byte_count', sa.Integer(), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('receipt', sa.JSON(), nullable=False),
    sa.Column('acquired_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['intake_works.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_id', 'raw_sha256')
    )
    with op.batch_alter_table('source_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_artifacts_work_id'), ['work_id'], unique=False)

    op.create_table('intake_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_id', sa.String(length=36), nullable=False),
    sa.Column('request_key', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('lease_owner', sa.String(length=36), nullable=False),
    sa.Column('lease_until', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['source_artifacts.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['intake_works.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_id', 'request_key')
    )
    with op.batch_alter_table('intake_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intake_attempts_work_id'), ['work_id'], unique=False)

    op.create_table('source_extractions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('parser_version', sa.String(length=100), nullable=False),
    sa.Column('normalized_sha256', sa.String(length=64), nullable=False),
    sa.Column('object_key', sa.String(length=250), nullable=False),
    sa.Column('passage_count', sa.Integer(), nullable=False),
    sa.Column('parsed_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['source_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', 'parser_version')
    )
    with op.batch_alter_table('source_extractions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_extractions_artifact_id'), ['artifact_id'], unique=False)

    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_extractions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_extractions_artifact_id'))

    op.drop_table('source_extractions')
    with op.batch_alter_table('intake_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intake_attempts_work_id'))

    op.drop_table('intake_attempts')
    with op.batch_alter_table('source_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_artifacts_work_id'))

    op.drop_table('source_artifacts')
    with op.batch_alter_table('intake_works', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intake_works_family_id'))

    op.drop_table('intake_works')
    op.drop_table('sec_request_budget')
    # ### end Alembic commands ###
